import { Achievement, Project, Experience, Testimonial } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    title: "Awardee PANDI Scholarship 2024",
    issuer: "PANDI (Pengelola Nama Domain Internet Indonesia)",
    image: "/pandi-award.jpg"
  },
  {
    title: "The Best bluAmbassador Telkom University",
    issuer: "blu by BCA Digital",
    image: "/bestblu.jpg"
  },
  {
    title: "The Best Digital Business Intern",
    issuer: "Motion Laboratory Telkom University",
    image: "/motion.jpg"
  },
  {
    title: "Project Funding Innovillage 2025",
    issuer: "Telkom Indonesia",
    image: "/innovillagefund.png"
  },
  {
    title: "1st Place Winner - National BPC Tirtayasa Entrepreneur Festival 2024",
    issuer: "UKM Kewirausahaan Untirta",
    image: "/kewirausahaanuntirta.jpeg"
  },
  {
    title: "1st Place Winner - Business Plan Motionhack 2025",
    issuer: "Motion Laboratory Telkom University",
    image: "/motionhack.png"
  },
  {
    title: "2nd Place Winner - International ASEAN BPC 3.0",
    issuer: "BO KST FT UNSRI",
    image: "/abc3.0.png"
  },
  {
    title: "2nd Place Winner - National ICT Business Development ITASE 6.0 2025",
    issuer: "HMSI Sistem informasi Telkom University Purwokerto",
    image: "/itase.png"
  },
  {
    title: "3rd Place Winner - National BPC Entrepreneur Day 2025",
    issuer: "UKM Kewirausahaan Politeknik Negeri Bandung",
    image: "/entrepreneurday.png"
  },
  {
    title: "3rd Place Winner - National Business Plan WGEC Competition 2025",
    issuer: "BEM FEB Universitas Wiraraja",
    image: "/wiraraja.png"
  },
  {
    title: "Digital Business Mentor",
    issuer: "Motion Laboratory Telkom University",
    image: "/digbismentor.jpg"
  },
  {
    title: "Speaker of Bootcamp Hackathon 2025",
    issuer: "SIECA FRI Telkom University",
    image: "/sieca.jpg"
  },
  {
    title: "BPC Mentor",
    issuer: "OPSIM Laboratory Telkom University",
    image: "/opsimlab.jpeg"
  },
];

export const PROJECTS: Project[] = [
  {
    id: "BIMO",
    title: "BIMO",
    role: "Project Leader, Brand Manager, Product Developer, System Architecture",
    period: "December 2025 - March 2026",
    description: "A smart monitoring system designed to optimize biogas production and enhance usage safety for rural households. It addresses the lack of real-time production data and safety concerns regarding gas leaks that previously hindered biogas adoption in villages",
    color: "#800000",
    location: { name: "Pasirhalang, Cisarua, Bandung Barat", lat: -6.827280, lng: 107.522122 },
    skills: ["Entrepreneurship", "Meta Ads", "Marketing Strategy", "Product Design"],
    image: "/BIMO/video.mp4",
    thumbnail: "/BIMO/video.mp4",
    category: "Community Service",
    device: "Mobile",
    associatedWith: "Telkom Indonesia",
    industry: "Renewable Energy",
    year: "2026",
    overview: "An integrated IoT-Mobile solution consisting of a hardware monitoring unit (pressure and MQ-4 gas sensors) and a mobile dashboard. The system provides real-time monitoring and an automatic safety shut-off/alert mechanism to prevent accidents.",
    goal: "To increase biogas utilization by 10-15% and reduce safety risks (leakage/excess pressure) by up to 90%, ultimately fostering energy independence and reducing reliance on conventional LPG.",
    approach: [
      { title: "Community-Based Co-Design", body: "A collaborative approach involving local experts and village residents to ensure the technology is practical, inclusive, and easily maintainable by the community." },
      { title: "SROI (Social Return on Investment)", body: "Applied to measure the economic and social value generated by the project, ensuring a sustainable impact on the village's economy and environment" }
    ],
    detailSkills: [
      "Project Management",
      "Strategic Leadership",
      "Community Engagement",
      "Social Innovation",
      "Product Design (Canva/Figma)",
      "Mobile App Development",
      "System Architecture Design."
    ],
    collage: [
      { type: 'video', src: '/BIMO/video.mp4', alt: 'BIMO video' },
      { type: 'image', src: '/BIMO/foto1.jpg', alt: 'BIMO foto1' },
      { type: 'image', src: '/BIMO/foto2.png', alt: 'BIMO foto2' },
    ]
  },
  {
    id: "aerobilliard",
    title: "AeroBilliard",
    role: "Project Leader, UI/UX Designer, System Analyst",
    period: "March 2025 - June 2025",
    description: "A business process transformation and UI/UX redesign for a Aerobilliard Pati to resolve operational bottlenecks and ordering errors.",
    color: "#0000FF",
    location: { name: "Pati", lat: -6.753006, lng: 111.041645 },
    skills: ["UI/UX Design", "Business Process Reengineering", "System Analysis"],
    image: "/Aerobilliard/video.mp4",
    thumbnail: "/Aerobilliard/video.mp4",
    category: "Digital Product",
    device: "Desktop",
    associatedWith: "AeroBilliard Pati",
    industry: "Sports, Entertainment",
    year: "2025",
    overview: "A high-performance desktop booking platform featuring an intuitive interface that streamlines table reservations and food/beverage orders.",
    goal: "To reduce manual ordering errors by 80%, optimize operational costs, and achieve a 'Best-in-Class' usability rating.",
    approach: [
      { title: "Business Process Reengineering (BPR)", body: "Instead of just fixing the UI, I re-evaluated and redesigned the entire workflow to eliminate redundant steps and reduce the potential for human error." },
      { title: "User-Centered Design", body: "An iterative design approach focusing on the end-user’s needs at every stage, resulting in a System Usability Scale (SUS) score of 93.125, categorizing the product as Excellent and highly intuitive." },
    ],
    detailSkills: [
      "User Research & Interviews",
      "UI/UX Design (Figma)",
      "Business Process Reengineering",
      "System Analysis",
      "Usability Testing (SUS)",
      "Prototyping",
      "Information Architecture"
    ],
    collage: [
      { type: 'video', src: '/Aerobilliard/video.mp4', alt: 'AeroBilliard video' },
      { type: 'image', src: '/Aerobilliard/image1.png', alt: 'AeroBilliard homepage' },
      { type: 'image', src: '/Aerobilliard/image2.png', alt: 'AeroBilliard store' },
    ],
  },
  {
    id: "training-odoo",
    title: "Training Odoo",
    role: "Project Leader, Strategic Liaison",
    period: "July 2025 - October 2025",
    description: "A strategic ERP education and certification initiative established between Odoo and Telkom University's Information Systems Department.",
    color: "#714B67",
    location: { name: "Telkom University", lat: -6.9740, lng: 107.6303 },
    skills: ["ERP", "Strategic Partnership", "Project Management", "Event Organizing", "Leadership"],
    image: "/TrainingOdoo/thumbnail.JPG",
    thumbnail: "/TrainingOdoo/thumbnail.JPG",
    articleUrl: "https://telkomuniversity.ac.id/erp-laboratory-telkom-university-dan-pt-odoo-software-indonesia-gelar-pelatihan-praktis-sistem-erp/",
    category: "Event",
    associatedWith: "Odoo Indonesia",
    industry: "Education, Technology, ERP",
    year: "2025",
    overview: "This collaboration project served as a bridge between academic theory and industrial practice, equipping students with essential hands-on skills in Odoo ERP software.",
    goal: "To provide in-depth understanding and practical experience in Odoo implementation while establishing a sustainable partnership for professional certification.",
    approach: [
      { title: "Strategic Partnership", body: "Initiated and managed high-level communication with PT Odoo Software Indonesia to align educational content with industry standards." },
      { title: "Large-Scale Execution", body: "MLed the end-to-end event lifecycle, managing logistics for 400+ participants and specialized technical training for 400+ students." },
      { title: "Hands-on Learning", body: "Facilitated direct practice sessions where participants configured and utilized various Odoo modules in a simulated business environment." }
    ],
    detailSkills: [
      "Event Management",
      "Strategic Partnership",
      "Public Relations",
      "ERP System (Odoo)",
      "Team Leadership",
      "Project Planning"
    ],
    collage: [
      { type: 'image', src: '/TrainingOdoo/thumbnail.JPG', alt: 'Training Odoo documentation' },
      { type: 'image', src: '/TrainingOdoo/image4.JPG', alt: 'Training Odoo documentation' },
      { type: 'image', src: '/TrainingOdoo/image2.JPG', alt: 'Training Odoo documentation' },
    ]
  },
  {
    id: "gardenese",
    title: "Gardenese",
    role: "Project Leader, Business Analyst, UI/UX Designer",
    period: "December 2024 - March 2025",
    description: "An integrated home gardening platform providing professional gardening services for urban dwellers.",
    color: "#008080",
    location: { name: "Telkom University", lat: -6.9740, lng: 107.6303 },
    skills: ["Business Development", "Market Analysis", "UI/UX", "Leadership"],
    image: "/Gardenese/thumbnail.png",
    thumbnail: "/Gardenese/thumbnail.png",
    category: "Digital Product",
    device: "Mobile",
    associatedWith: "Telkom University",
    industry: "Home Gardening & Agri-Tech",
    year: "2024",
    overview: "Gardenese addresses the challenges of urban farming by offering an all-in-one ecosystem that includes a marketplace for gardening supplies, expert consultations, and smart plant maintenance features",
    goal: "To simplify the gardening experience for urban communities through technology, ensuring sustainable and successful home-scale plant cultivation",
    approach: [
      { title: "Product Strategy & Analysis", body: "Conducted deep market research and financial planning (TAM, SAM, SOM) to validate the business model and identify key customer pain points." },
      { title: "User-Centric UI/UX Design", body: "Designed high-fidelity mobile prototypes using Figma, focusing on a seamless user journey for features like AI plant scanning and expert booking." },
      { title: "Project Leadership", body: "Managed the end-to-end development process, coordinating cross-functional tasks to ensure the product vision aligned with market needs and feasibility." }
    ],
    detailSkills: [
      "User Research",
      "Vusiness Model Canvas",
      "Financial Forecasting",
      "Product Design (Canva/Figma)",
      "Prototyping",
      "Mobile App Development",
      "Stakeholder Analysis",
    ],
    collage: [
      { type: 'image', src: '/Gardenese/thumbnail.png', alt: 'Gardenese thumbnail' },
      { type: 'image', src: '/Gardenese/image1.png', alt: 'Gardenese motto' },
      { type: 'video', src: '/Gardenese/video1.mp4', alt: 'Gardenese MVP' },
    ]
  }
];

export const CAREERS: Experience[] = [
  {
    title: "bluAmbassador Telkom",
    company: "blu by BCA Digital",
    period: "August 2024 - August 2025",
    description: "• Promoted blu by BCA Digital to potential customers through various online and offline channels\n• Achieved Top 1 Influence for making a significant impact through promotional activities and Top 2 Education for contributing to user education on blu's features",
    image: "/blutelkom.jpeg",
    skills: ["Public Speaking", "Digital Marketing", "Influence"]
  },
  {
    title: "Administration Assistant",
    company: "CV Aristha Prima",
    period: "April 2021 - April 2025",
    description: "• Collected and recorded data for over 2000 vehicles used in the implementation of Universitas Diponegoro's KKN program\n• Coordinated with team members to organize departure and pickup schedules for students",
    image: "",
    skills: ["Administration", "Data Entry"]
  },
  {
    title: "Founder & Owner",
    company: "Telyuwear.co",
    period: "Jun 2024 - Jul 2024",
    description: "• Established and managed a fashion and design business, specializing in the production and sale of Telkom University uniforms and custom lanyards.\n• Led marketing efforts through various channels, successfully reaching and serving over 100 customers.\n• Oversaw the entire production process, from concept design to product distribution, while maintaining strong customer satisfaction and retention.",
    image: "",
    skills: ["Business Strategy", "Entrepreneurship", "Digital Marketing", "Product Management"]
  }
];

export const ORGANIZATIONS: Experience[] = [
  {
    title: "Head of Project Division",
    company: "ERP Laboratory Telkom University",
    period: "January 2026 - Present",
    description: "• Manage and coordinate collaborations between internal and external projects within the Information Systems program in the ERP Laboratory scope.\n• Lead a team of 10 project division members in executing work programs and project initiatives related to ERP development.\n• Served as chief organizer for a collaboration event with Odoo, facilitating hands- on ERP training sessions and strengthening the lab's industry partnership.",
    image: "projecterp.jpeg",
    skills: ["Leadership", "ERP", "Project Management"]
  },
  {
    title: "Project Manager",
    company: "Motion Laboratory Telkom University",
    period: "August 2025 - Present",
    description: "• Successfully managed and delivered more than 2 digital business projects, achieving over 90% of KPI targets related to timeline, quality, and innovation outcomes.\n• Served as a Digital Business Mentor, guiding new interns in business model development and financial project management.",
    image: "pmmotion.jpeg",
    skills: ["Leadership", "Project Management", "Project Development"]
  },
  {
    title: "Media & Public Relation Staff",
    company: "SEARCH Telkom University",
    period: "May 2025 - January 2026",
    description: "• Contributed to increasing event visibility and engagement through strategic media relations and public communication. \n• Initiated and executed 2 'Search Talk' sessions, moderating discussions with high-achieving university students to share insights and experiences.\n• Represented the organization as a main speaker in the 'Search x AdbisJuara' podcast, delivering organizational insights and engaging with a broader audience",
    image: "mpr.JPG",
    skills: ["Marketing Strategy", "Public Speaking", "Partnership"]
  },
  {
    title: "Vice President",
    company: "Mudik Roadshow KOMPILASI 2025",
    period: "March 2024 - February 2025",
    description: "• Assisted the chair in leading over 40 members to promote Telkom University in high schools across Pati.\n• Coordinated promotional activities and events to enhance the university's visibility and appeal to potential students.",
    image: "kompilasi.jpg",
    skills: ["Event Organizer", "Leadership", "Marketing Strategy"]
  },
  {
    title: "President",
    company: "OSBIT SMA Negeri 1 Pati",
    period: "June 2021 - June 2022",
    description: "• Led and coordinated a team of over 50 organization members, ensuring smooth operations and effective teamwork. \n• Taught coding and design skills to members, enhancing their technical abilities and knowledge. \n• Contributed to the school's technological advancement by organizing multiple tech-focused events and initiatives.",
    image: "osbit.jpg",
    skills: ["Leadership", "Team Management", "IT"]
  },
];

export const EDUCATIONS: Experience[] = [
  {
    title: "Bachelor of Computer Science, 3.85/4.00",
    company: "Telkom University",
    period: "September 2023 - April 2026 (Expected)",
    description: "• Achieved 7+ national and international business competition awards.\n• Selected as a funded innovation project awardee (Innovillage) supported by Telkom Indonesia. Appointed as Mentor and Judge for SIECA Hackathon, Faculty of Industrial Engineering.\n• Selected as Digital Business Mentor and Project Manager at Motion Laboratory.\n• Chosen as a PANDI Scholarship Awardee 2024 (Indonesian Domain Name Registry).\n• Received multiple academic and achievement awards from the Faculty of Industrial Engineering.",
    image: "",
    skills: ["Information Systems, ERP, Business Analysis", "Teaching"]
  },
  {
    title: "High School Diploma, 90.96/100.00",
    company: "SMA Negeri 1 Pati",
    period: "2021 - 2023",
    description: "• Served as President (Chairperson) of the school organization OSBIT during senior high school. \n• Appointed as Head of Documentation and Film Division for SMANSADAY Anniversary 2022.",
    image: "",
    skills: ["Leadership", "IT"]
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "Joshua is a lifesaver when it comes to SAP. He made complex ERP modules actually make sense during our lab sessions.",
    author: "Information Systems Student",
    role: "Mentee"
  },
  {
    quote: "He doesn't just manage projects; he owns them. Seeing him hit 90% of KPIs at Motion Lab was seriously impressive.",
    author: "Motion Lab Leader",
    role: "Colleague"
  },
  {
    quote: "A natural at building partnerships. The Odoo collaboration wouldn't have been this massive without his strategic touch.",
    author: "Head of Study Program",
    role: "Supervisor"
  },
  {
    quote: "I’ve seen Joshua lead the BIMO project, and his ability to turn tech into something useful for real families is top-tier.",
    author: "Project Partner",
    role: "Collaborator"
  },
  {
    quote: "Super sharp marketing instincts. He scaled Telyuwear from zero to 100+ customers like it was second nature.",
    author: "Telyuwear Team",
    role: "Business Partner"
  },
  {
    quote: "He’s the go-to person for anything",
    author: "Fellow bluAmbassador",
    role: "Teammate"
  },
  {
    quote: "He teaches you how to think like a founder. Best mentor I've had so far.",
    author: "SIECA Mentee",
    role: "Mentee"
  }
];

export const SKILLS = [
  "ERP", "Project Management", "Web Dev", "Figma", "Meta Ads"
];
